// Run: node companion/web/test/hlp.test.js
const assert = require('assert');
const H = require('../hlp.js');
const V = require('../../test-vectors.json');
const te = new TextEncoder();

assert.strictEqual(H.hex(H.sha256(te.encode('abc'))), 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
assert.strictEqual(H.hex(H.sha256(new Uint8Array(1000000).fill(97))), 'cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0');
assert.strictEqual(H.hex(H.hmac(new Uint8Array(20).fill(0x0b), te.encode('Hi There'))), 'b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7');
assert.strictEqual(H.hex(H.hkdf(H.unhex('000102030405060708090a0b0c'), new Uint8Array(22).fill(0x0b), H.unhex('f0f1f2f3f4f5f6f7f8f9'), 42)),
  '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865');
assert.strictEqual(H.hex(H.poly1305(H.unhex('85d6be7857556d337f4452fe42d506a80103808afb0db2fd4abff6af4149f51b'), te.encode('Cryptographic Forum Research Group'))), 'a8061dc1305136c6c22b8baf0c0127a9');
{
  const key = Uint8Array.from({ length: 32 }, (_, i) => 0x80 + i);
  const nonce = H.unhex('070000004041424344454647');
  const aad = H.unhex('50515253c0c1c2c3c4c5c6c7');
  const pt = te.encode("Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.");
  const s = H.seal(key, nonce, aad, pt);
  assert.strictEqual(H.hex(s.subarray(0, 16)), 'd31a8d34648e60db7b86afbc53ef7ec2');
  assert.strictEqual(H.hex(s.subarray(s.length - 16)), '1ae10b594f09e26a7e902ecbd0600691');
  assert.deepStrictEqual(H.open(key, nonce, aad, s), pt);
  s[5] ^= 1;
  assert.strictEqual(H.open(key, nonce, aad, s), null);
}
// Interop with the HydatekOS kernel (vectors generated by tests-host)
{
  const c = new H.Session(H.unhex(V.key), H.unhex(V.client_nonce), H.unhex(V.server_nonce), true);
  V.c2s_plain.forEach((p, i) => assert.strictEqual(H.hex(c.seal(H.unhex(p))), V.c2s[i], 'c2s frame ' + i));
  V.s2c.forEach((f, i) => assert.strictEqual(H.hex(c.open(H.unhex(f))), V.s2c_plain[i], 's2c frame ' + i));
  const m = H.decodeMsg(H.unhex(V.c2s_plain[1]));
  assert.strictEqual(m.op, 'file');
  assert.strictEqual(m.blob.length, 256);
}
{
  const e = H.encodeMsg('msg', { text: 'a\nb\\c=d', thread: '1' }, new Uint8Array([1, 10, 10, 2]));
  const d = H.decodeMsg(e);
  assert.deepStrictEqual(d.fields, { text: 'a\nb\\c=d', thread: '1' });
  assert.deepStrictEqual(Array.from(d.blob), [1, 10, 10, 2]);
}
{
  const t0 = Date.now();
  const key = new Uint8Array(32).fill(3);
  const big = new Uint8Array(4 << 20);
  const s = H.seal(key, new Uint8Array(12), new Uint8Array(0), big);
  assert.ok(H.open(key, new Uint8Array(12), new Uint8Array(0), s));
  console.log('4 MB seal+open:', Date.now() - t0, 'ms');
}
console.log('hlp.js: all tests passed');
